// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"CustomLogo","status":true,"description":"Shows RPG Maker and user logos at the start of the game.","parameters":{"logo1":"","logo1ImageName":"MadeWithMv","logo1Skippable":"true","logo1Coordinate":"","logo1X":"408","logo1Y":"312","logo1Origin":"0.5","logo1Time":"","logo1FadeinFrames":"12","logo1FadeoutFrames":"12","logo1DurationFrames":"120","logo2":"","logo2ImageName":"","logo2Skippable":"true","logo2Coordinate":"","logo2X":"408","logo2Y":"312","logo2Origin":"0.5","logo2Time":"","logo2FadeinFrames":"12","logo2FadeoutFrames":"12","logo2DurationFrames":"120","logo3":"","logo3ImageName":"","logo3Skippable":"true","logo3Coordinate":"","logo3X":"408","logo3Y":"312","logo3Origin":"0.5","logo3Time":"","logo3FadeinFrames":"12","logo3FadeoutFrames":"12","logo3DurationFrames":"120","allowTotalSkip":"true"}},
{"name":"MC_Core","status":true,"description":"Core do Mundo Central: IDs semânticos e helpers comuns.","parameters":{}},
{"name":"SRPG_core","status":true,"description":"SRPG Gear MV core 1.24Q (pinned upstream).","parameters":{"WithYEP_BattleEngineCore":"false","WithCommunityBasic_CoreScript":"false","srpgTroopID":"1","srpgBattleSwitchID":"91","existActorVarID":"91","existEnemyVarID":"92","turnVarID":"93","activeEventID":"94","targetEventID":"95","battleDistanceID":"96","defaultMove":"4","srpgAutoBattleStateId":"0","srpgMenuCommandList":"turnEnd,winLose,status,options,save,gameEnd","Use Map Battle":"3","useAgiAttackPlus":"false","srpgBattleReaction":"3","Refocus Camera":"false","srpgSet":"!srpg_set_type1"}},
{"name":"SRPG_AoE","status":true,"description":"Required SRPG Gear AoE module (pinned upstream).","parameters":{}},
{"name":"SRPG_RangeControl","status":true,"description":"Required SRPG Gear range/passability module (pinned upstream).","parameters":{}},
{"name":"MC_TacticalBridge","status":true,"description":"Bridge isolada do Mundo Central para o spike tático T02.","parameters":{}},
{"name":"MC_TextWrap","status":true,"description":"Quebra automática de palavras nas mensagens.","parameters":{}},
{"name":"MC_WorldMap","status":true,"description":"Mapa-múndi e fast travel do Mundo Central.","parameters":{}}
];
